apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
    role: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    name: mongo
    role: mongo
  template:
    metadata:
      labels:
        name: mongo
        role: mongo
      name: mongo
    spec:
      containers:
      - args:
        - --replSet
        - rs0
        - --oplogSize
        - "500"
        image: mongo:3.2.0
        imagePullPolicy: Always
        name: mongo
        ports:
        - containerPort: 27017
          name: mongo
          protocol: TCP
        volumeMounts:
        - mountPath: /data/db/
          name: mongo-disk
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - gcePersistentDisk:
          fsType: ext4
          pdName: replaymongo1
        name: mongo-disk
