apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  clusterIP: None
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: mongo
    role: mongo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
