apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: replay
  name: replay
spec:
  replicas: 1
  selector:
    app: replay
  template:
    metadata:
      labels:
        app: replay
    spec:
      containers:
      - command:
        - bash
        - -c
        - source /etc/kube-replay/config && node main.js
        image: paralin/dota-replay:latest
        imagePullPolicy: Always
        name: replay
        ports:
        - containerPort: 80
          name: web
        - containerPort: 10304
          name: desktop
        volumeMounts:
        - mountPath: /etc/kube-replay
          name: replay-config
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: replay-config
        secret:
          secretName: replay-config
