apiVersion: v1
kind: ReplicationController
metadata:
  name: replay-vN
  labels:
    name: replay
    app: replay
    version: vN
    tier: api
  replicas: 1
spec:
  selector:
    app: replay
    version: vN
  template:
    metadata:
      labels:
        name: replay
        app: replay
        tier: api
        version: vN
    spec:
      containers:
      - name: replay
        image: r.prompt.life:30000/prompt/replay:vN
        command: [ "bash", "-c", "source /etc/kube-replay/config && node main.js" ]
        volumeMounts:
          - name: replay-config
            mountPath: /etc/kube-replay
            readOnly: true
        ports:
        - containerPort: 80
        - containerPort: 10304
      volumes:
        - name: replay-config
          secret:
            secretName: replay-config
